[http]
port = 3000

[mqtt]
topics = ["topic"]
broker = "localhost"
port = 1883
user = "user"
password = "password"

[azureServiceBus]
enabled = false
connectionString = ""
interval = 1000
queues = ["myqueue"]