[http]
port = 3000

[display]
leds = 42

[mqtt]
topics = ["topic"]
broker = "localhost"
port = 1883
user = "user"
password = "password"

[azureServiceBus]
enabled = true
connectionString = "Endpoint=get-from-azure"
interval = 1000
queues = ["neosegment"]